# fly.toml app configuration file generated for compliment-of-the-day on 2025-09-21T17:27:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'compliment-of-the-day'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
